name: null
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=4.6.0
  - aom=3.5.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=24.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.1.0
  - blosc=1.21.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.32.3
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=3.4.0
  - code-server=4.16.1
  - comm=0.2.2
  - contourpy=1.3.0
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cycler=0.12.1
  - dav1d=1.2.1
  - dbus=1.13.18
  - debugpy=1.8.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - eigen=3.4.0
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - ffmpeg=4.2.3
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.54.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - giflib=5.2.2
  - glib=2.80.2
  - glib-tools=2.80.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.6.13
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - hpack=4.0.0
  - httpcore=1.0.6
  - httpx=0.27.2
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.10
  - imagecodecs=2023.1.23
  - imageio=2.36.0
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.5
  - intel-openmp=2022.1.0
  - ipykernel=6.29.5
  - ipython=8.28.0
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.15
  - ld_impl_linux-64=2.43
  - lerc=3.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcups=2.3.3
  - libcurand=10.3.5.147
  - libcurl=8.1.2
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.2
  - libgomp=14.1.0
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.58.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libpng=1.6.43
  - libpq=12.17
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libuv=1.46.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - markupsafe=3.0.1
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql=5.7.20
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.6
  - networkx=3.3
  - nodejs=16.20.2
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - opencv=4.10.0
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.3.2
  - overrides=7.7.0
  - packaging=24.1
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=0.5.6
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.48
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pyparsing=3.1.4
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytorch=2.4.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywavelets=1.7.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qt-main=5.15.2
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.20.0
  - scikit-image=0.24.0
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=75.1.0
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.46.0
  - stack_data=0.6.2
  - statsmodels=0.14.4
  - sympy=1.13.3
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tifffile=2023.8.12
  - tinycss2=1.3.0
  - tk=8.6.13
  - tomli=2.0.2
  - torchaudio=2.4.1
  - torchtriton=3.0.0
  - torchvision=0.19.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241003
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - uri-template=1.3.0
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - x264=1!152.20180806
  - xkeyboard-config=2.42
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.20.2
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - altair==5.4.1
      - antlr4-python3-runtime==4.9.3
      - black==24.10.0
      - blinker==1.8.2
      - cachetools==5.5.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - easyocr==1.7.2
      - faker==30.3.0
      - favicon==0.7.0
      - fsspec==2024.9.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grpcio==1.66.2
      - htbuilder==0.6.2
      - hydra-core==1.3.2
      - iopath==0.1.9
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markdownlit==0.0.7
      - mdurl==0.1.2
      - more-itertools==10.5.0
      - mypy-extensions==1.0.0
      - narwhals==1.9.3
      - ninja==1.11.1.1
      - omegaconf==2.3.0
      - pathspec==0.12.1
      - plotly==5.24.1
      - portalocker==2.10.1
      - protobuf==5.28.2
      - pyarrow==17.0.0
      - pyclipper==1.3.0.post5
      - pycocotools==2.0.8
      - pydeck==0.9.1
      - pymdown-extensions==10.11.2
      - python-bidi==0.6.3
      - rich==13.9.2
      - shapely==2.0.6
      - smmap==5.0.1
      - st-annotated-text==4.0.1
      - st-theme==1.2.3
      - streamlit==1.39.0
      - streamlit-camera-input-live==0.2.0
      - streamlit-card==1.0.2
      - streamlit-embedcode==0.1.2
      - streamlit-extras==0.5.0
      - streamlit-faker==0.0.3
      - streamlit-image-coordinates==0.1.9
      - streamlit-keyup==0.2.4
      - streamlit-toggle-switch==1.0.2
      - streamlit-vertical-slider==2.5.5
      - tabulate==0.9.0
      - tenacity==9.0.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - toml==0.10.2
      - tqdm==4.66.5
      - validators==0.34.0
      - watchdog==5.0.3
      - werkzeug==3.0.4
      - yacs==0.1.8
